// MintRedeemController — user entry point for the fUSD hub.
//
// Orchestrates USDC SAC transfers, CCTP settlement processing,
// fUSD token mint/burn, and remote mint authorization issuance.
// Delegates canonical accounting to VaultAccounting.

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype, symbol_short,
    Address, BytesN, Env,
};

// ── External contract client stubs ────────────────────────────────────────────
// In production: generated by soroban-sdk from the deployed contract ABI.

mod fusd_token {
    soroban_sdk::contractimport!(
        file = "../../../target/wasm32-unknown-unknown/release/fusd_token.wasm"
    );
}

mod vault_accounting {
    soroban_sdk::contractimport!(
        file = "../../../target/wasm32-unknown-unknown/release/vault_accounting.wasm"
    );
}

// ── Storage keys ──────────────────────────────────────────────────────────────

#[contracttype]
pub enum DataKey {
    Admin,
    FusdToken,
    VaultAccounting,
    UsdcSac,          // Stellar USDC SAC address
    FeeVersion,       // current active fee config version
    MintFeeBps,
    RedeemFeeBps,
    FeeRecipient,
    Paused,
}

// ── Redeem request (two-phase state machine for remote redeems) ───────────────

#[contracttype]
#[derive(Clone, Debug)]
pub struct RedeemRequest {
    pub id: BytesN<32>,
    pub user: Address,
    pub amount_6: i128,
    pub destination_domain: u32,
    pub destination_recipient: BytesN<32>,
    pub status: RedeemStatus,
    pub created_ledger: u32,
}

#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub enum RedeemStatus {
    BurnAccepted,
    BurnAcceptedSendFailed,
    Sent,
    Completed,
    RemintIssued,
}

#[contracttype]
pub enum DataKeyExt {
    RedeemRequest(BytesN<32>),
    ConsumedBurn(BytesN<32>),
}

// ── Contract ─────────────────────────────────────────────────────────────────

#[contract]
pub struct MintRedeemController;

#[contractimpl]
impl MintRedeemController {
    // ── Initialisation ────────────────────────────────────────────────────────

    pub fn initialize(
        e: Env,
        admin: Address,
        fusd_token: Address,
        vault_accounting: Address,
        usdc_sac: Address,
        mint_fee_bps: u32,
        redeem_fee_bps: u32,
        fee_recipient: Address,
    ) {
        assert!(!e.storage().instance().has(&DataKey::Admin), "already initialized");
        admin.require_auth();
        e.storage().instance().set(&DataKey::Admin, &admin);
        e.storage().instance().set(&DataKey::FusdToken, &fusd_token);
        e.storage().instance().set(&DataKey::VaultAccounting, &vault_accounting);
        e.storage().instance().set(&DataKey::UsdcSac, &usdc_sac);
        e.storage().instance().set(&DataKey::MintFeeBps, &mint_fee_bps);
        e.storage().instance().set(&DataKey::RedeemFeeBps, &redeem_fee_bps);
        e.storage().instance().set(&DataKey::FeeRecipient, &fee_recipient);
        e.storage().instance().set(&DataKey::FeeVersion, &1_u32);
        e.storage().instance().set(&DataKey::Paused, &false);
    }

    // ── Local Stellar deposit → fUSD mint ─────────────────────────────────────
    //
    // Flow:
    //   user approves USDC SAC to this contract
    //   -> deposit_usdc called
    //   -> USDC transferred from user (7 decimals)
    //   -> floored to 6 decimals; dust returned or retained
    //   -> VaultAccounting.record_local_deposit(net_6)
    //   -> VaultAccounting.mint_liability_from_settled_usdc(amount_after_fee_6)
    //   -> FusdToken.controller_mint(user, amount_after_fee_6)

    pub fn deposit_usdc(
        e: Env,
        user: Address,
        amount_7: i128,    // Stellar SAC USDC (7 decimals)
        min_fusd_6: i128,  // slippage guard
        min_fee_version: u32,
    ) {
        user.require_auth();
        Self::assert_active(&e);
        assert!(amount_7 > 0, "amount must be positive");

        // Fee version check — stale-quote protection.
        let fee_version: u32 = e.storage().instance().get(&DataKey::FeeVersion).unwrap();
        assert!(fee_version == min_fee_version, "FeeVersionMismatch");

        // Transfer USDC from user.
        let usdc_sac: Address = e.storage().instance().get(&DataKey::UsdcSac).unwrap();
        Self::usdc_transfer(&e, &usdc_sac, &user, &e.current_contract_address(), amount_7);

        // Floor to 6 decimals. Return seventh-decimal dust to user.
        let amount_6 = amount_7 / 10;
        assert!(amount_6 > 0, "amount too small after decimal conversion");
        let dust_7 = amount_7 - (amount_6 * 10);
        if dust_7 > 0 {
            Self::usdc_transfer(&e, &usdc_sac, &e.current_contract_address(), &user, dust_7);
            e.events().publish((symbol_short!("DustRet"), user.clone()), dust_7);
        }

        // Apply mint fee.
        let mint_fee_bps: u32 = e.storage().instance().get(&DataKey::MintFeeBps).unwrap();
        let fee_6 = (amount_6 * mint_fee_bps as i128) / 10_000;
        let net_6 = amount_6 - fee_6;
        assert!(net_6 >= min_fusd_6, "slippage: min_fusd not met");

        // Collect fee.
        if fee_6 > 0 {
            let fee_recipient: Address = e.storage().instance().get(&DataKey::FeeRecipient).unwrap();
            e.events().publish((symbol_short!("FeeCol"),), fee_6);
            // In production: transfer fee_6 in USDC to fee_recipient here.
            let _ = fee_recipient;
        }

        // Accounting: credit net deposit, create liability, mint fUSD.
        let vault: vault_accounting::Client = Self::vault_client(&e);
        vault.record_local_deposit(&e.current_contract_address(), &net_6);
        vault.mint_liability_from_settled_usdc(&e.current_contract_address(), &net_6);

        let fusd: fusd_token::Client = Self::fusd_client(&e);
        fusd.controller_mint(&e.current_contract_address(), &user, &net_6);

        e.events().publish((symbol_short!("DepLoc"), user), net_6);
    }

    // ── Local Stellar burn → USDC redemption ─────────────────────────────────
    //
    // Flow:
    //   user calls redeem_local
    //   -> FusdToken.controller_burn(user, fusd_amount)
    //   -> VaultAccounting.burn_liability_for_redemption(amount_6)
    //   -> transfer USDC (7 decimals) to user
    //   -> VaultAccounting.mark_outbound_sent

    pub fn redeem_local(
        e: Env,
        user: Address,
        fusd_amount_6: i128,
        min_usdc_7: i128,
        min_fee_version: u32,
    ) {
        user.require_auth();
        Self::assert_active(&e);
        assert!(fusd_amount_6 > 0, "amount must be positive");

        // Fee version check.
        let fee_version: u32 = e.storage().instance().get(&DataKey::FeeVersion).unwrap();
        assert!(fee_version == min_fee_version, "FeeVersionMismatch");

        // Apply redeem fee.
        let redeem_fee_bps: u32 = e.storage().instance().get(&DataKey::RedeemFeeBps).unwrap();
        let fee_6 = (fusd_amount_6 * redeem_fee_bps as i128) / 10_000;
        let net_6 = fusd_amount_6 - fee_6;

        // Burn fUSD from user.
        let fusd: fusd_token::Client = Self::fusd_client(&e);
        fusd.controller_burn(&e.current_contract_address(), &user, &fusd_amount_6);

        // Reduce liability by full burned amount; only net_6 moves through pending_outbound.
        // Fee portion stays in settled_idle_usdc_6 as retained protocol income.
        let vault: vault_accounting::Client = Self::vault_client(&e);
        vault.burn_liability_for_redemption(&e.current_contract_address(), &fusd_amount_6, &net_6);

        // Send USDC (7-decimal) to user.
        let out_7 = net_6 * 10;
        assert!(out_7 >= min_usdc_7, "slippage: min_usdc_7 not met");

        let usdc_sac: Address = e.storage().instance().get(&DataKey::UsdcSac).unwrap();
        Self::usdc_transfer(&e, &usdc_sac, &e.current_contract_address(), &user, out_7);
        vault.mark_outbound_sent(&e.current_contract_address(), &net_6);

        e.events().publish((symbol_short!("RedLoc"), user), net_6);
    }

    // ── Inbound CCTP settlement → fUSD mint (or remote mint auth) ────────────
    //
    // Called by the off-chain CCTP relayer after Circle attestation.
    // The relayer does NOT supply the credited amount — it is computed from
    // balance delta (CC-CRIT-1 fix). The relayer only supplies proof materials.
    //
    // In production: integrate with Stellar CCTP MessageTransmitter contract.
    // In this PoC: simulate attestation with a mock hash for testability.

    pub fn receive_cctp_settlement(
        e: Env,
        caller: Address,         // relayer or anyone (permissionless submission)
        cctp_message_hash: BytesN<32>,
        source_domain: u32,
        source_sender: BytesN<32>,  // must match allowlisted remote router
        destination_chain_id: u32,  // which chain the user wants fUSD on
        destination_recipient: BytesN<32>,
        finalized: bool,
        // `amount_6` is NOT taken from the caller.
        // In production the controller calls Stellar CCTP receive_message,
        // then computes: net_received_6 = balance_after - balance_before.
        // For the PoC we accept a mock_balance_delta for testability.
        mock_net_received_6: i128,
    ) {
        caller.require_auth();
        Self::assert_active(&e);

        // TODO production: validate source_sender against ChainState.remote_router
        let _ = source_sender;

        // Validate destination chain is active (loaded from VaultAccounting).
        // In production: call vault.chain_state(destination_chain_id).active

        let vault: vault_accounting::Client = Self::vault_client(&e);

        // The net_received_6 here is the balance-delta from the CCTP receive call,
        // not the CCTP message amount. This prevents relayer amount injection.
        vault.record_inbound_settlement(
            &e.current_contract_address(),
            &cctp_message_hash,
            &mock_net_received_6,
            &source_domain,
            &finalized,
        );

        if !finalized {
            // Fast-credit path: fUSD minted against insurance reserve, not confirmed collateral.
            // For the PoC, skip the actual fast-credit mint and emit an event.
            e.events().publish(
                (symbol_short!("FastCrd"), destination_chain_id),
                mock_net_received_6,
            );
            return;
        }

        // Finalized: consume mint_allowance and mint fUSD on target chain.
        vault.mint_liability_from_settled_usdc(
            &e.current_contract_address(),
            &mock_net_received_6,
        );

        if destination_chain_id == 0 {
            // Destination is Stellar: mint fUSD locally.
            // In production decode recipient from BytesN<32> to Stellar Address.
            // For PoC: mint to a placeholder address derived from recipient bytes.
            let placeholder = e.current_contract_address(); // stand-in for decoded recipient
            let fusd: fusd_token::Client = Self::fusd_client(&e);
            fusd.controller_mint(&e.current_contract_address(), &placeholder, &mock_net_received_6);

            e.events().publish(
                (symbol_short!("MintLoc"), source_domain),
                mock_net_received_6,
            );
        } else {
            // Destination is a spoke: issue remote mint authorization via GMP.
            // mint_auth_id = hash("FUSD_REMOTE_MINT_AUTH_V1" || canonical_payload)
            // For PoC: derive a deterministic id from hash inputs.
            let auth_id = Self::derive_mint_auth_id(&e, &cctp_message_hash, destination_chain_id);

            // depositor_chain_id: source_domain (cross-chain deposit)
            vault.authorize_remote_mint(
                &e.current_contract_address(),
                &auth_id,
                &destination_chain_id,
                &mock_net_received_6,
                &(e.ledger().sequence() + 172_800), // ~60 day expiry
                &source_domain,
                &source_sender,
            );

            // In production: send RemoteMintAuthorize GMP via Axelar to destination spoke.
            e.events().publish(
                (symbol_short!("RemAuth"), destination_chain_id),
                mock_net_received_6,
            );
        }
    }

    // ── Accept remote burn notice (spoke burn → Stellar hub → CCTP out) ───────
    //
    // Called when an authenticated RemoteBurnNotice GMP arrives from a spoke.
    // After hub acceptance, the hub sends native USDC via CCTP to the destination.

    pub fn accept_spoke_burn(
        e: Env,
        caller: Address,
        burn_id: BytesN<32>,
        source_chain_id: u32,
        amount_6: i128,
        destination_domain: u32,
        usdc_recipient: BytesN<32>,
    ) {
        caller.require_auth();
        Self::assert_active(&e);
        assert!(amount_6 > 0);

        let vault: vault_accounting::Client = Self::vault_client(&e);

        // 1. Accept the burn — reduces chain outstanding_supply_6.
        vault.accept_remote_burn(
            &e.current_contract_address(),
            &burn_id,
            &source_chain_id,
            &amount_6,
        );

        // 2. Reduce global liability and reserve outbound USDC.
        // Cross-chain redeems carry no fee, so burned == out.
        vault.burn_liability_for_redemption(&e.current_contract_address(), &amount_6, &amount_6);

        // 3. In production: call Stellar CCTP deposit_for_burn to send USDC.
        //    Here we emit the intent event and store the redeem request.
        let redeem_id = Self::derive_redeem_id(&e, &burn_id, source_chain_id);
        let req = RedeemRequest {
            id: redeem_id.clone(),
            user: caller.clone(),
            amount_6,
            destination_domain,
            destination_recipient: usdc_recipient,
            status: RedeemStatus::BurnAccepted,
            created_ledger: e.ledger().sequence(),
        };
        e.storage().persistent().set(&DataKeyExt::RedeemRequest(redeem_id.clone()), &req);

        e.events().publish(
            (symbol_short!("BurnAcc"), source_chain_id),
            amount_6,
        );
        e.events().publish(
            (symbol_short!("CctpOut"), destination_domain),
            amount_6,
        );
    }

    // ── Receive RemoteMintExecuted ack from spoke ─────────────────────────────

    pub fn confirm_remote_mint_executed(
        e: Env,
        caller: Address,
        mint_auth_id: BytesN<32>,
    ) {
        caller.require_auth();
        let vault: vault_accounting::Client = Self::vault_client(&e);
        vault.confirm_remote_mint_executed(&e.current_contract_address(), &mint_auth_id);
        e.events().publish((symbol_short!("AckConf"),), mint_auth_id);
    }

    // ── Retry / remint recovery for failed CCTP sends ────────────────────────

    pub fn retry_redeem_cctp_send(e: Env, caller: Address, redeem_id: BytesN<32>) {
        caller.require_auth();
        let mut req: RedeemRequest = e.storage().persistent()
            .get(&DataKeyExt::RedeemRequest(redeem_id.clone()))
            .expect("redeem not found");
        assert!(
            req.status == RedeemStatus::BurnAcceptedSendFailed,
            "not in SendFailed state"
        );
        // In production: re-call Stellar CCTP deposit_for_burn.
        req.status = RedeemStatus::Sent;
        e.storage().persistent().set(&DataKeyExt::RedeemRequest(redeem_id), &req);
        e.events().publish((symbol_short!("RetryCC"),), req.amount_6);
    }

    pub fn remint_on_redeem_failure(
        e: Env,
        caller: Address,
        redeem_id: BytesN<32>,
        remint_recipient: Address,
    ) {
        caller.require_auth();
        let mut req: RedeemRequest = e.storage().persistent()
            .get(&DataKeyExt::RedeemRequest(redeem_id.clone()))
            .expect("redeem not found");
        assert!(
            req.status == RedeemStatus::BurnAcceptedSendFailed,
            "not in SendFailed state"
        );

        let vault: vault_accounting::Client = Self::vault_client(&e);
        // Step 1: Cancel the outbound that never left — returns USDC from pending back to idle.
        vault.cancel_pending_outbound(&e.current_contract_address(), &req.amount_6);
        // Step 2: Re-create the fUSD liability (idle/pending are already correct after step 1).
        vault.restore_failed_redeem_liab(&e.current_contract_address(), &req.amount_6);

        let fusd: fusd_token::Client = Self::fusd_client(&e);
        fusd.controller_mint(&e.current_contract_address(), &remint_recipient, &req.amount_6);

        req.status = RedeemStatus::RemintIssued;
        e.storage().persistent().set(&DataKeyExt::RedeemRequest(redeem_id), &req);

        e.events().publish((symbol_short!("Remint"), remint_recipient), req.amount_6);
    }

    // ── Governance ────────────────────────────────────────────────────────────

    pub fn pause(e: Env, caller: Address) {
        Self::auth_admin(&e, &caller);
        e.storage().instance().set(&DataKey::Paused, &true);
        e.events().publish((symbol_short!("Paused"),), ());
    }

    pub fn unpause(e: Env, caller: Address) {
        Self::auth_admin(&e, &caller);
        e.storage().instance().set(&DataKey::Paused, &false);
    }

    // Fee management: only Manager-submitted ManagerFeeConfig (no fee_recipient field).
    // CRIT-1 fix: fee_recipient is NOT in this call; governance uses set_fee_recipient.
    pub fn manager_set_fees(e: Env, manager: Address, mint_fee_bps: u32, redeem_fee_bps: u32) {
        manager.require_auth();
        // In production: verify manager role against RoleRegistry.
        assert!(mint_fee_bps <= 100, "mint fee exceeds governance-set max (1%)");
        assert!(redeem_fee_bps <= 100, "redeem fee exceeds governance-set max (1%)");

        e.storage().instance().set(&DataKey::MintFeeBps, &mint_fee_bps);
        e.storage().instance().set(&DataKey::RedeemFeeBps, &redeem_fee_bps);

        // Bump version so in-flight quotes become invalid.
        let v: u32 = e.storage().instance().get(&DataKey::FeeVersion).unwrap_or(1);
        e.storage().instance().set(&DataKey::FeeVersion, &(v + 1));
    }

    pub fn set_fee_recipient(e: Env, caller: Address, recipient: Address) {
        Self::auth_admin(&e, &caller);
        e.storage().instance().set(&DataKey::FeeRecipient, &recipient);
    }

    pub fn fee_version(e: Env) -> u32 {
        e.storage().instance().get(&DataKey::FeeVersion).unwrap_or(1)
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    fn vault_client(e: &Env) -> vault_accounting::Client {
        let addr: Address = e.storage().instance().get(&DataKey::VaultAccounting).unwrap();
        vault_accounting::Client::new(e, &addr)
    }

    fn fusd_client(e: &Env) -> fusd_token::Client {
        let addr: Address = e.storage().instance().get(&DataKey::FusdToken).unwrap();
        fusd_token::Client::new(e, &addr)
    }

    fn usdc_transfer(e: &Env, sac: &Address, from: &Address, to: &Address, amount_7: i128) {
        // In production: call USDC SAC transfer.
        // For PoC: emit a transfer event and trust the caller owns the balance.
        e.events().publish(
            (symbol_short!("UsdcXfr"), from.clone(), to.clone()),
            amount_7,
        );
        let _ = sac;
    }

    fn derive_mint_auth_id(e: &Env, settlement_hash: &BytesN<32>, dest_chain: u32) -> BytesN<32> {
        // Production: hash("FUSD_REMOTE_MINT_AUTH_V1" || full canonical payload).
        // PoC: xor settlement hash with chain id for determinism.
        let mut bytes = settlement_hash.to_array();
        let chain_bytes = dest_chain.to_be_bytes();
        for i in 0..4 {
            bytes[28 + i] ^= chain_bytes[i];
        }
        BytesN::from_array(e, &bytes)
    }

    fn derive_redeem_id(e: &Env, burn_id: &BytesN<32>, source_chain: u32) -> BytesN<32> {
        let mut bytes = burn_id.to_array();
        let chain_bytes = source_chain.to_be_bytes();
        for i in 0..4 {
            bytes[24 + i] ^= chain_bytes[i];
        }
        BytesN::from_array(e, &bytes)
    }

    fn assert_active(e: &Env) {
        let paused: bool = e.storage().instance().get(&DataKey::Paused).unwrap_or(false);
        assert!(!paused, "controller paused");
    }

    fn auth_admin(e: &Env, caller: &Address) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        assert!(*caller == admin, "not admin");
        caller.require_auth();
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod test {
    // Integration tests are in tests/integration.rs which registers all three
    // contracts together in one Soroban test environment.
    // Unit stubs are kept minimal here because the controller's logic depends
    // heavily on cross-contract calls to FusdToken and VaultAccounting.
}
